package dev.sassine.api.structure.export.builder;

import static org.apache.commons.text.CaseUtils.toCamelCase;
import static org.apache.logging.log4j.LogManager.getLogger;

import java.util.List;

import org.apache.logging.log4j.Logger;

import dev.sassine.api.structure.export.builder.factory.ClassSourceFactory;
import dev.sassine.api.structure.model.java.EntityModel;

public class ClassSourceBuilder extends ClassSourceFactory {
	
	private static final Logger log = getLogger();
	
	private static final char CHAR = '_';

	
	public static ClassSourceBuilder init() {
		return new ClassSourceBuilder();
	}

	public void build(List<EntityModel> entityModel, boolean useAutoGenerated, String packageName) {
		log.debug("Starting build Class Source ");
		log.debug("Parameters ::: isAutoGenerated: {} | PackageName {}", useAutoGenerated, packageName);
		entityModel.forEach(e -> build(e, useAutoGenerated, packageName));
	}

	private void build(EntityModel entityModel,boolean useAutoGenerated, String packageName) {
		String nameClass = toCamelCase(entityModel.getName(), true, CHAR);
		createEntity().execute(entityModel, useAutoGenerated, nameClass, packageName);
		createDTO().execute(entityModel, useAutoGenerated, nameClass, packageName);
		createRepository().execute(entityModel, useAutoGenerated, nameClass, packageName);
	}
	
}
