package dev.sassine.api.structure.export.builder.factory;

import dev.sassine.api.structure.model.java.EntityModel;

public interface Factory {
	void execute(EntityModel entityModel,boolean isAutoGenerated, String nameClass, String packageName);
}
