package dev.sassine.api.structure;

import static dev.sassine.api.structure.export.DatabaseConverter.convert;
import static dev.sassine.api.structure.export.builder.BuilderEntity.build;
import static dev.sassine.api.structure.type.TypeConverter.convertTypeFromSQLToEntityStore;
import static dev.sassine.api.structure.util.Util.read;
import static dev.sassine.api.structure.validation.DatabaseValidator.validate;

import java.io.FileInputStream;
import java.io.InputStream;
import java.util.List;

import dev.sassine.api.structure.model.java.EntityModel;
import dev.sassine.api.structure.model.sql.Database;
import dev.sassine.api.structure.parser.SqlImport;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class Sqlschema2Java {

	public void compile(String inputFile,boolean isPostgress,boolean isAutoGenerated) {
		inputFile = "C:\\poc\\poc.sql";
		log.debug("preparing to read SQL file('{}') ", inputFile);
		try (InputStream in = new FileInputStream(inputFile)) {
			log.debug("file read successfully");
			process(read(in),isPostgress,isAutoGenerated);
		} catch (final Exception e) {
			log.error(e.getMessage(), e);
		}
	}
	
	private void process(final String sqlContent, boolean isPostgress, boolean isAutoGenerated) {
		Database database = new SqlImport().getDatabase(sqlContent);
		convertTypeFromSQLToEntityStore(database,isPostgress);
		validate(database);
		List<EntityModel> entityModel = convert(database);
		build(entityModel,isAutoGenerated);
	}

}
