package dev.sassine.api.structure.export.builder.factory.impl;

import static dev.sassine.api.structure.export.builder.function.ImportBeanFunction.importEntityClass;
import static dev.sassine.api.structure.export.builder.function.ImportBeanFunction.importJavaTime;
import static dev.sassine.api.structure.export.builder.function.StoreClassFuncation.store;
import static java.lang.String.format;
import static java.lang.reflect.Modifier.PUBLIC;
import static org.apache.logging.log4j.LogManager.getLogger;

import java.lang.reflect.Modifier;

import org.apache.logging.log4j.Logger;
import org.burningwave.core.classes.AnnotationSourceGenerator;
import org.burningwave.core.classes.ClassSourceGenerator;
import org.burningwave.core.classes.FunctionSourceGenerator;
import org.burningwave.core.classes.TypeDeclarationSourceGenerator;
import org.burningwave.core.classes.UnitSourceGenerator;
import org.burningwave.core.classes.VariableSourceGenerator;

import com.fasterxml.jackson.annotation.JsonProperty;

import dev.sassine.api.structure.export.builder.factory.Factory;
import dev.sassine.api.structure.model.java.EntityModel;
import dev.sassine.api.structure.model.java.FieldModel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

public class DTOFactory implements Factory {

	private static final Logger log = getLogger();
	
	private static final String PACKAGE_DTO_NAME = "dto";
	private static final String METHOD_TO_ENTITY = "toEntity";
	private static final String METHOD_RETURN_ENTITY = "return entity;";
	private static final String FORMAT_DTO_CLASSNAME = "%sDTO";
	private static final String FORMAT_ENTITY_CLASSNAME = "%sEntity";
	private static final String FORMAT_NEW_ENTITY_METHOD = "%s entity = new %s();";
	private static final String FORMAT_STRING_FIELDS = "\"%s\"";
	private static final String FORMAT_PACKAGE_DOT_PACKAGE = "%s.%s";
	private static final String FORMAT_SETTER_EQ_GETTER = "this.%s = entity.get%s();";
	private static final String PARAM_VALUE = "value";
	
	@Override
	public void execute(EntityModel entityModel,boolean isAutoGenerated, String nameClass, String packageName) {
		log.debug("ClassName: ({}) - PackageName: ({}) ", nameClass, packageName);
		UnitSourceGenerator gen = this.buildPackage(packageName);
		log.debug("Package builded");
		ClassSourceGenerator clDTO = this.buildClassSource(nameClass);
		log.debug("ClassDTO builded");
		importEntityClass(nameClass, packageName, gen);
		String nameEntityClass = format(FORMAT_ENTITY_CLASSNAME, nameClass);
		log.debug("Prepared EntityClassName  ({})",nameEntityClass);
		FunctionSourceGenerator fm = this.startFunctionMethod(nameEntityClass);
		log.debug("Started functionMethod toEntity");
		log.debug("Prepare generate ({}) fields", entityModel.getFields().size());
		entityModel.getFields().forEach(fieldModel -> {
			VariableSourceGenerator field = this.buildField(fieldModel);
			importJavaTime(gen, fieldModel);
			this.addFunctionToMethodFunction(fm, fieldModel);
			log.debug("Adding field in functionMethod toEntity");
			clDTO.addField(field);
			log.debug("Field ({}) builded", fieldModel.getName());
		});
		
		this.closeMethodFunction(fm);
		log.debug("Closed functionMethod toEntity");
		clDTO.addMethod(fm);
		gen.addClass(clDTO);
		store(gen);
		log.debug("ClassDTO ({}) stored", nameClass);
	}

	private void closeMethodFunction(FunctionSourceGenerator functionMethodToEntity) {
		functionMethodToEntity.addBodyCodeLine(METHOD_RETURN_ENTITY);
	}

	private void addFunctionToMethodFunction(FunctionSourceGenerator functionMethodToEntity, FieldModel fieldModel) {
		functionMethodToEntity.addBodyCodeLine(format(FORMAT_SETTER_EQ_GETTER, fieldModel.getCamelName(), fieldModel.getCamelNameUpper()));
	}

	private VariableSourceGenerator buildField(FieldModel fieldModel) {
		return VariableSourceGenerator
				.create(TypeDeclarationSourceGenerator.create(fieldModel.getType()), fieldModel.getCamelName())
				.addModifier(Modifier.PRIVATE)
				.addAnnotation(AnnotationSourceGenerator.create(JsonProperty.class)
				.addParameter(PARAM_VALUE,VariableSourceGenerator.create(format(FORMAT_STRING_FIELDS, fieldModel.getName()))));
	}

	private FunctionSourceGenerator startFunctionMethod(String nameEntityClass) {
		return FunctionSourceGenerator
				.create(METHOD_TO_ENTITY)
				.addModifier(PUBLIC).setReturnType(nameEntityClass)
				.addBodyCodeLine(format(FORMAT_NEW_ENTITY_METHOD, nameEntityClass, nameEntityClass));
	}

	private ClassSourceGenerator buildClassSource(String nameClass) {
		return ClassSourceGenerator
				.create(TypeDeclarationSourceGenerator.create(format(FORMAT_DTO_CLASSNAME, nameClass)))
				.addModifier(PUBLIC).addAnnotation(AnnotationSourceGenerator.create(Getter.class))
				.addAnnotation(AnnotationSourceGenerator.create(Setter.class))
				.addAnnotation(AnnotationSourceGenerator.create(NoArgsConstructor.class));
	}

	private UnitSourceGenerator buildPackage(String packageName) {
		return UnitSourceGenerator.create(format(FORMAT_PACKAGE_DOT_PACKAGE, packageName, PACKAGE_DTO_NAME));
	}

}
