name: Compute coverage

on:
  push:
    branches: [ main , develop ]


jobs:
  compute-coverage:
    name: Compute coverage
    runs-on: ubuntu-latest
    environment:
      name: coveralls
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build and test
        run: cd sqlschema2java-core && mvn clean test jacoco:report coveralls:report -DrepoToken=${{ secrets.coveralls_repo_token }}
