name: Compute coverage

on:
  push:
    branches: [ main , develop ]


jobs:
  compute-coverage:
    name: Compute coverage
    runs-on: ubuntu-latest
    environment:
      name: coveralls
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.5.0
        with:
          java-version: 8
          distribution: 'zulu'
          architecture: x64
      - name: Build and test
        run: cd sqlschema2java-core && mvn clean test run-coveralls jacoco:report coveralls:report -DrepoToken=${{ secrets.coveralls_repo_token }}
