name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish-core:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package SQLSchema2Java Core
        run: | 
            cd sqlschema2java-core
            mvn --batch-mode deploy 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  deploy-await:
    runs-on: ubuntu-latest
    needs:  publish-core
    steps:
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '5m'
  
  publish-maven-plugin:
    runs-on: ubuntu-latest 
    environment:
      name: plugin
    permissions: 
      contents: read
      packages: write 
    needs:  deploy-await
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package SQLSchema2Java Core
        run: | 
            cd sqlschema2java-maven-plugin
            mvn --batch-mode deploy 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
