name: Publish package Sonatype - Maven Central
on:
  release:
    types: [created]
jobs:
  deploy-core:
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 30 minutes
      uses: jakejarvis/wait-action@master
      with:
        time: '30m'
  deploy-plugin:
    runs-on: ubuntu-latest
    environment:
      name: plugin
    needs:  deploy-core
    steps:
    - name: Sleep for 30 minutes
      uses: jakejarvis/wait-action@master
      with:
        time: '30m'      